# 01 Import libraries

In [1]:
import pandas as pd
import numpy as np
import os

# 02 Import data and path set up

In [2]:
df = pd.read_csv(r'C:\Users\christina.savva\Documents\Data Immersion 6\02 Data\Original\Listings - Detailed.csv', index_col = False)

In [3]:
path = r'C:\Users\christina.savva\Documents\Data Immersion 6'

In [4]:
path

'C:\\Users\\christina.savva\\Documents\\Data Immersion 6'

# 03 Review data

In [7]:
df.shape

(3723, 92)

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3723 entries, 0 to 3722
Data columns (total 92 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   id                                3723 non-null   int64
 1   listing_url                       3723 non-null   object
 2   scrape_id                         3723 non-null   int64
 3   last_scraped                      3723 non-null   object
 4   name                              3723 non-null   object
 5   summary                           3457 non-null   object
 6   space                             2977 non-null   object
 7   description                       3722 non-null   object
 8   experiences_offered               3723 non-null   object
 9   neighborhood_overview             2469 non-null   object
 10  notes                             1712 non-null   object
 11  transit                           2588 non-null   object
 12  thumbnail_url                     3690 non-null   object
 13  medium_url                        3690 non-null   object
 14  picture_url                       3723 non-null   object
 15  xl_picture_url                    3690 non-null   object
 16  host_id                           3723 non-null   int64
 17  host_url                          3723 non-null   object
 18  host_name                         3723 non-null   object
 19  host_since                        3723 non-null   object
 20  host_location                     3717 non-null   object
 21  host_about                        2763 non-null   object
 22  host_response_time                3289 non-null   object
 23  host_response_rate                3289 non-null   object
 24  host_acceptance_rate              3109 non-null   object
 25  host_is_superhost                 3723 non-null   object
 26  host_thumbnail_url                3723 non-null   object
 27  host_picture_url                  3723 non-null   object
 28  host_neighbourhood                3461 non-null   object
 29  host_listings_count               3723 non-null   int64
 30  host_total_listings_count         3723 non-null   int64
 31  host_verifications                3723 non-null   object
 32  host_has_profile_pic              3723 non-null   object
 33  host_identity_verified            3723 non-null   object
 34  street                            3723 non-null   object
 35  neighbourhood                     3370 non-null   object
 36  neighbourhood_cleansed            3723 non-null   object
 37  neighbourhood_group_cleansed      0 non-null      float64
 38  city                              3723 non-null   object
 39  state                             3723 non-null   object
 40  zipcode                           3714 non-null   object
 41  market                            3723 non-null   object
 42  smart_location                    3723 non-null   object
 43  country_code                      3723 non-null   object
 44  country                           3723 non-null   object
 45  latitude                          3723 non-null   float64
 46  longitude                         3723 non-null   float64
 47  is_location_exact                 3723 non-null   object
 48  property_type                     3722 non-null   object
 49  room_type                         3723 non-null   object
 50  accommodates                      3723 non-null   int64
 51  bathrooms                         3696 non-null   float64
 52  bedrooms                          3702 non-null   float64
 53  beds                              3712 non-null   float64
 54  bed_type                          3723 non-null   object
 55  amenities                         3723 non-null   object
 56  square_feet                       82 non-null     float64
 57  price                             3723 non-null   object
 58  weekly_price                      2124 non-null   object
 59  monthly_price                     1807 non-null   object
 60  security_deposit                  1426 non-null   object
 61  cleaning_fee                      2335 non-null   object
 62  guests_included                   3723 non-null   int64
 63  extra_people                      3723 non-null   object
 64  minimum_nights                    3723 non-null   int64
 65  maximum_nights                    3723 non-null   int64
 66  calendar_updated                  3723 non-null   object
 67  has_availability                  3723 non-null   object
 68  availability_30                   3723 non-null   int64
 69  availability_60                   3723 non-null   int64
 70  availability_90                   3723 non-null   int64
 71  availability_365                  3723 non-null   int64
 72  calendar_last_scraped             3723 non-null   object
 73  number_of_reviews                 3723 non-null   int64
 74  first_review                      2893 non-null   object
 75  last_review                       2893 non-null   object
 76  review_scores_rating              2855 non-null   float64
 77  review_scores_accuracy            2848 non-null   float64
 78  review_scores_cleanliness         2847 non-null   float64
 79  review_scores_checkin             2847 non-null   float64
 80  review_scores_communication       2851 non-null   float64
 81  review_scores_location            2851 non-null   float64
 82  review_scores_value               2851 non-null   float64
 83  requires_license                  3723 non-null   object
 84  license                           1 non-null      float64
 85  jurisdiction_names                3697 non-null   object
 86  instant_bookable                  3723 non-null   object
 87  cancellation_policy               3723 non-null   object
 88  require_guest_profile_picture     3723 non-null   object
 89  require_guest_phone_verification  3723 non-null   object
 90  calculated_host_listings_count    3723 non-null   int64
 91  reviews_per_month                 2893 non-null   float64
dtypes: float64(16), int64(15), object(61)
memory usage: 2.6+ MB

# 04 Removing unnecessary columns

In [15]:
df = df.drop(columns = ['listing_url', 'scrape_id', 'last_scraped', 'space', 'description', 'experiences_offered', 'neighborhood_overview', 'notes', 'transit', 'thumbnail_url', 'medium_url', 'picture_url', 'xl_picture_url', 'host_url', 'host_name', 'host_location', 'host_about', 'host_thumbnail_url', 'host_picture_url', 'host_neighbourhood', 'host_total_listings_count', 'neighbourhood_group_cleansed', 'market', 'country_code', 'country', 'amenities', 'square_feet', 'has_availability', 'calendar_last_scraped', 'requires_license', 'license', 'jurisdiction_names', 'calendar_updated'])

In [16]:
# dropped 33 columns

df.shape

(3723, 59)

# 05 Consistency checks

In [19]:
# finding missing values

df.isnull().sum()

id                                     0
name                                   0
summary                              266
host_id                                0
host_since                             0
host_response_time                   434
host_response_rate                   434
host_acceptance_rate                 614
host_is_superhost                      0
host_listings_count                    0
host_verifications                     0
host_has_profile_pic                   0
host_identity_verified                 0
street                                 0
neighbourhood                        353
neighbourhood_cleansed                 0
city                                   0
state                                  0
zipcode                                9
smart_location                         0
latitude                               0
longitude                              0
is_location_exact                      0
property_type                          1
room_type                              0
accommodates                           0
bathrooms                             27
bedrooms                              21
beds                                  11
bed_type                               0
price                                  0
weekly_price                        1599
monthly_price                       1916
security_deposit                    2297
cleaning_fee                        1388
guests_included                        0
extra_people                           0
minimum_nights                         0
maximum_nights                         0
availability_30                        0
availability_60                        0
availability_90                        0
availability_365                       0
number_of_reviews                      0
first_review                         830
last_review                          830
review_scores_rating                 868
review_scores_accuracy               875
review_scores_cleanliness            876
review_scores_checkin                876
review_scores_communication          872
review_scores_location               872
review_scores_value                  872
instant_bookable                       0
cancellation_policy                    0
require_guest_profile_picture          0
require_guest_phone_verification       0
calculated_host_listings_count         0
reviews_per_month                    830
dtype: int64

In [20]:
# remving columns with too many missing values

df = df.drop(columns = ['host_response_time', 'host_response_rate', 'host_acceptance_rate', 'neighbourhood', 'weekly_price', 'monthly_price'])

In [21]:
df.shape

(3723, 53)

In [28]:
# re-running missing values

df.isnull().sum()

id                                     0
name                                   0
summary                              266
host_id                                0
host_since                             0
host_is_superhost                      0
host_listings_count                    0
host_verifications                     0
host_has_profile_pic                   0
host_identity_verified                 0
street                                 0
neighbourhood_cleansed                 0
city                                   0
state                                  0
zipcode                                9
smart_location                         0
latitude                               0
longitude                              0
is_location_exact                      0
property_type                          1
room_type                              0
accommodates                           0
bathrooms                             27
bedrooms                              21
beds                                  11
bed_type                               0
price                                  0
security_deposit                    2297
cleaning_fee                        1388
guests_included                        0
extra_people                           0
minimum_nights                         0
maximum_nights                         0
availability_30                        0
availability_60                        0
availability_90                        0
availability_365                       0
number_of_reviews                      0
first_review                         830
last_review                          830
review_scores_rating                 868
review_scores_accuracy               875
review_scores_cleanliness            876
review_scores_checkin                876
review_scores_communication          872
review_scores_location               872
review_scores_value                  872
instant_bookable                       0
cancellation_policy                    0
require_guest_profile_picture          0
require_guest_phone_verification       0
calculated_host_listings_count         0
reviews_per_month                    830
dtype: int64

In [29]:
# remving more columns with missing values that are not relevant

df = df.drop(columns = ['bathrooms', 'bedrooms', 'beds'])

In [30]:
# re-running missing values

df.isnull().sum()

id                                     0
name                                   0
summary                              266
host_id                                0
host_since                             0
host_is_superhost                      0
host_listings_count                    0
host_verifications                     0
host_has_profile_pic                   0
host_identity_verified                 0
street                                 0
neighbourhood_cleansed                 0
city                                   0
state                                  0
zipcode                                9
smart_location                         0
latitude                               0
longitude                              0
is_location_exact                      0
property_type                          1
room_type                              0
accommodates                           0
bed_type                               0
price                                  0
security_deposit                    2297
cleaning_fee                        1388
guests_included                        0
extra_people                           0
minimum_nights                         0
maximum_nights                         0
availability_30                        0
availability_60                        0
availability_90                        0
availability_365                       0
number_of_reviews                      0
first_review                         830
last_review                          830
review_scores_rating                 868
review_scores_accuracy               875
review_scores_cleanliness            876
review_scores_checkin                876
review_scores_communication          872
review_scores_location               872
review_scores_value                  872
instant_bookable                       0
cancellation_policy                    0
require_guest_profile_picture          0
require_guest_phone_verification       0
calculated_host_listings_count         0
reviews_per_month                    830
dtype: int64

In [31]:
# Replace missing values in 'summary' column with N/A based on there not being any entries

df['summary'].fillna('N/A', inplace=True)

In [32]:
# re-running missing values

df.isnull().sum()

id                                     0
name                                   0
summary                                0
host_id                                0
host_since                             0
host_is_superhost                      0
host_listings_count                    0
host_verifications                     0
host_has_profile_pic                   0
host_identity_verified                 0
street                                 0
neighbourhood_cleansed                 0
city                                   0
state                                  0
zipcode                                9
smart_location                         0
latitude                               0
longitude                              0
is_location_exact                      0
property_type                          1
room_type                              0
accommodates                           0
bed_type                               0
price                                  0
security_deposit                    2297
cleaning_fee                        1388
guests_included                        0
extra_people                           0
minimum_nights                         0
maximum_nights                         0
availability_30                        0
availability_60                        0
availability_90                        0
availability_365                       0
number_of_reviews                      0
first_review                         830
last_review                          830
review_scores_rating                 868
review_scores_accuracy               875
review_scores_cleanliness            876
review_scores_checkin                876
review_scores_communication          872
review_scores_location               872
review_scores_value                  872
instant_bookable                       0
cancellation_policy                    0
require_guest_profile_picture          0
require_guest_phone_verification       0
calculated_host_listings_count         0
reviews_per_month                    830
dtype: int64

In [24]:
# finding duplicate values

df_dupes = df[df.duplicated()]

In [25]:
df_dupes

Empty DataFrame
Columns: [id, name, summary, host_id, host_since, host_is_superhost, host_listings_count, host_verifications, host_has_profile_pic, host_identity_verified, street, neighbourhood_cleansed, city, state, zipcode, smart_location, latitude, longitude, is_location_exact, property_type, room_type, accommodates, bathrooms, bedrooms, beds, bed_type, price, security_deposit, cleaning_fee, guests_included, extra_people, minimum_nights, maximum_nights, availability_30, availability_60, availability_90, availability_365, number_of_reviews, first_review, last_review, review_scores_rating, review_scores_accuracy, review_scores_cleanliness, review_scores_checkin, review_scores_communication, review_scores_location, review_scores_value, instant_bookable, cancellation_policy, require_guest_profile_picture, require_guest_phone_verification, calculated_host_listings_count, reviews_per_month]
Index: []

[0 rows x 53 columns]

In [26]:
# checking whether a DF contains any mixed-type columns

for col in df.columns.tolist():
  weird = (df[[col]].applymap(type) != df[[col]].iloc[0].apply(type)).any(axis = 1)
  if len (df[weird]) > 0:
    print (col)

summary
zipcode
property_type
security_deposit
cleaning_fee
first_review
last_review

# 06 Running summary statistics

In [22]:
df.describe()

,id,host_id,host_listings_count,latitude,longitude,accommodates,bathrooms,bedrooms,beds,guests_included,...,number_of_reviews,review_scores_rating,review_scores_accuracy,review_scores_cleanliness,review_scores_checkin,review_scores_communication,review_scores_location,review_scores_value,calculated_host_listings_count,reviews_per_month
count,3.723000e+03,3.723000e+03,3723.000000,3723.000000,3723.000000,3723.000000,3696.000000,3702.000000,3712.000000,3723.000000,...,3723.000000,2855.00000,2848.000000,2847.000000,2847.000000,2851.000000,2851.000000,2851.000000,3723.000000,2893.000000
mean,4.798778e+06,1.497402e+07,13.517325,38.913967,-77.023294,3.195004,1.256358,1.210157,1.643319,1.622079,...,15.306742,93.42627,9.540730,9.330875,9.710924,9.752718,9.386180,9.323395,3.174590,1.803446
std,2.639497e+06,1.351108e+07,64.534408,0.021647,0.026951,2.012216,0.585539,0.839851,1.182117,1.348598,...,29.645586,7.77311,0.790103,1.050435,0.672492,0.605433,0.890065,0.836415,6.123187,1.765808
min,3.192000e+03,1.585000e+03,1.000000,38.825061,-77.110525,1.000000,0.000000,0.000000,1.000000,0.000000,...,0.000000,30.00000,2.000000,2.000000,2.000000,3.000000,4.000000,2.000000,1.000000,0.010000
25%,2.482238e+06,3.433722e+06,1.000000,38.901789,-77.039859,2.000000,1.000000,1.000000,1.000000,1.000000,...,1.000000,90.00000,9.000000,9.000000,10.000000,10.000000,9.000000,9.000000,1.000000,0.560000
50%,5.002566e+06,1.037275e+07,1.000000,38.913375,-77.026410,2.000000,1.000000,1.000000,1.000000,1.000000,...,4.000000,95.00000,10.000000,10.000000,10.000000,10.000000,10.000000,9.000000,1.000000,1.110000
75%,7.148024e+06,2.433087e+07,3.000000,38.926509,-77.002798,4.000000,1.000000,1.000000,2.000000,2.000000,...,16.000000,100.00000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,2.000000,2.500000
max,8.688666e+06,4.555465e+07,480.000000,38.996382,-76.913137,16.000000,8.000000,10.000000,16.000000,16.000000,...,362.000000,100.00000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,41.000000,10.980000

# 07 Exporting DF

In [34]:
df.to_csv(os.path.join(path, '02 Data', 'Cleaned', 'listings_cleaned.csv'))